// Generated by https://quicktype.io

export interface Company {
    _id:       string;
    name:      string;
    isActive:  boolean;
    createdAt: string;
    updatedAt: string;
    __v:       number;
}
